USE [BWorks]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Bicycles](
 [BicycleId] [int] IDENTITY(1,1) NOT NULL,
 [CycleName] [varchar](max) NOT NULL,
 [CycleImage] [varchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
 [BicycleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
