# Sample CI/CD Pipeline Configuration
on:
  push:
    branches:
      - main

# Define the jobs within each stage
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: echo "yarn install or npm install"
