# Sample CI/CD Pipeline Configuration
on:
  push:
    branches:
      - main

# Define the stages for the pipeline
stages:
  - build

# Define the jobs within each stage
jobs:
  build:
    stage: build
    script:
      - echo "Starting the build process..."
