# Sample CI/CD Pipeline Configuration
name: circleci CI/CD Pipeline

on:
  push:
    branches:
      - main

# Define the jobs within each stage
jobs:
  - name: build-job
    stage: build
    script:
      - echo "Starting the build process..."
      - echo "Compiling source code..."
      - echo "Running unit tests..."
      - echo "Build complete."
